### ISSUE TITLE
Fused layer norm cuda not found

### ISSUE THREAD

**Issue by JeetRoy97** [yumoxu/querysum#10]
![Screenshot from 2021-08-24 00-50-22](https://user-images.githubusercontent.com/59523992/130505719-0c516ca8-6f03-4425-9e9c-1fbbdb77fdb1.png)
I tried both of @yumoxu  ways suggested, but still getting errors. Kindly help.

**Comment by yumoxu** [comment]
Please double check if you have installed `apex` properly.
