### ISSUE TITLE
Missing links for TD-QFS data

### ISSUE THREAD

**Issue by GuilaumeBrassard** [yumoxu/querysum#3]
Hello!

I am not able to access TD-QFS data from the first link as it seems to be restricted to members of your university. Moreover, the second link for the processed data seems to be missing. Both are in the "Prepare benchmark data" in the README file.

Futhermore, I wonder if there is a script which could process the DUC data to match "querysum/data" folder.

Thanks!

**Comment by yumoxu** [comment]
Hi, thanks for spotting this! I have updated the two links (raw and processed) for TD-QFS.

For DUC benchmarks, after acquiring the data from NIST, you can gather each year's clusters, summaries, and queries under `data/docs`, `data/summary_targets` and `data/topics`, respectively. For instance, DUC 2006's clusters, queries, summaries should be found under `data/docs/2006/`, `data/topics/2006.sgml` and `data/summary_targets/2006/`, respectively. This instruction has been added to `README`.

**Comment by GuilaumeBrassard** [comment]
Hello again!

Thanks for updating fast! The link worked but I am facing an issue when I run the src/frame/ir/ir_tf.py file. When importing the config_loader.py, the torch.load() function appears to cause an error since there is no file named /data/lm953/summarization/querysum/model/qa_sentence. I suppose we need to download a file in the model/qa_sentence folder and use the torch.load() with the path and filename, but I am not sure where to get this file.

Thanks for the support!

**Comment by yumoxu** [comment]
You are right! Trained models used in the paper can be downloaded [here](https://drive.google.com/file/d/1lOb9ECZa_fsYCI7Q41xMQjL0fzFvpkkD/view?usp=sharing).

Originally I put this link in the next **Answering** section, but it should be prepared before running the pipeline. I have also updated `README` to make it clear.
