### ISSUE TITLE
A question about the max-pooling operation in the paper

### ISSUE THREAD

**Issue by elevenofji** [yumoxu/querysum#5]
In Equ (9)  of this paper, there is a max-pooling operation. What does _(0,1)_  mean? I think you choose the biggest value in _Q_, and _q^P_e_ in Equ (10) is equal to the _q_ in Equ (9), for every sentence in the selected sentence sets from the span extraction estimator. Is it right?

**Comment by yumoxu** [comment]
Hi @elevenofji, thanks for the questions! (0, 1) simply denotes the value range of q.

And your understanding of Eq (10) and Eq (9) is accurate!
