### ISSUE TITLE
DUC data

### ISSUE THREAD

**Issue by JaniceXiong** [yumoxu/querysum#6]
Hi! I have requested DUC data, but the content seems different from your description. It seems that it only has doc?
![image](https://user-images.githubusercontent.com/43976565/123269053-2ec97300-d531-11eb-82cd-7d8de80a639e.png)
![image](https://user-images.githubusercontent.com/43976565/123269118-4274d980-d531-11eb-9955-13a2bc00af06.png)
And I found topic sgml file in NIST website, but it also looks weird...
![image](https://user-images.githubusercontent.com/43976565/123269455-941d6400-d531-11eb-975c-13e8d312e987.png)
Could you check whether there is wrong with my data or not? Thanks!

**Comment by wglazer** [comment]
`duc2006_docs.tar.gz` is actually a linux compressed file, see [here](https://www.howtogeek.com/362203/what-is-a-tar.gz-file-and-how-do-i-open-it/)
To uncompress in Windows, see this [thread](https://superuser.com/questions/215629/how-to-open-a-tar-gz-file-in-windows)
Once this is done, you can put the uncompressed folders where they belong and rename them by year

**Comment by yumoxu** [comment]
Hi @JaniceXiong, please see suggestions from @williamGlazer about uncompressing `.tar.gz` files. On Linux simply do:

`tar -xzvf duc2006_docs.tar.gz`

For the `.sgml` file, simply put it under `data/topics` and rename it to `2006.sgml`.

Let me know if there is any further problem.

**Comment by JaniceXiong** [comment]
Thanks @yumoxu @williamGlazer 
I have got "docs" from "duc2006_docs.tar.gz" and "topics" from website, but where are the "summary targets"?

**Comment by Dceaser** [comment]
> Hi! I have requested DUC data, but the content seems different from your description. It seems that it only has doc?
> ![image](https://user-images.githubusercontent.com/43976565/123269053-2ec97300-d531-11eb-82cd-7d8de80a639e.png)
> ![image](https://user-images.githubusercontent.com/43976565/123269118-4274d980-d531-11eb-9955-13a2bc00af06.png)
> And I found topic sgml file in NIST website, but it also looks weird...
> ![image](https://user-images.githubusercontent.com/43976565/123269455-941d6400-d531-11eb-975c-13e8d312e987.png)
> Could you check whether there is wrong with my data or not? Thanks!

Hi @JaniceXiong , I have also requested DUC data, but the content in my browser seems different from your image description
![image](https://user-images.githubusercontent.com/59682980/130323570-8b0c6f7f-3fd1-4f05-b5e9-af8ebbf8927c.png)
I can't find the document like duc2006_docs.tar.gz in your image, could you show me how you get it, thanks

**Comment by JeetRoy97** [comment]
> > Hi! I have requested DUC data, but the content seems different from your description. It seems that it only has doc?
> > ![image](https://user-images.githubusercontent.com/43976565/123269053-2ec97300-d531-11eb-82cd-7d8de80a639e.png)
> > ![image](https://user-images.githubusercontent.com/43976565/123269118-4274d980-d531-11eb-9955-13a2bc00af06.png)
> > And I found topic sgml file in NIST website, but it also looks weird...
> > ![image](https://user-images.githubusercontent.com/43976565/123269455-941d6400-d531-11eb-975c-13e8d312e987.png)
> > Could you check whether there is wrong with my data or not? Thanks!
> 
> Hi @JaniceXiong , I have also requested DUC data, but the content in my browser seems different from your image description
> ![image](https://user-images.githubusercontent.com/59682980/130323570-8b0c6f7f-3fd1-4f05-b5e9-af8ebbf8927c.png)
> I can't find the document like duc2006_docs.tar.gz in your image, could you show me how you get it, thanks

It would be provided to you by NIST.

**Comment by Dceaser** [comment]
Thanks for your answer @JeetRoy97

**Comment by Dceaser** [comment]
Thanks @JeetRoy97
Maybe my statement is not very clear, I asked my tutor last week, and found our laboratory have applied for a login account before, so I just log in by the account. But the dataset I have downloaded is very different from others

**Comment by Dceaser** [comment]
@JeetRoy97 
Maybe my statement is not very clear, I asked my tutor last week, and found our laboratory had applied for a login account before, so I just logged in by the account. But the dataset I have downloaded is very different from others

**Comment by Dceaser** [comment]
Thanks @JeetRoy97 
Maybe my statement is not very clear, I asked my tutor last week, and found our laboratory had applied for a login account before, so I just logged in by the account. But the dataset I have downloaded is very different from others

**Comment by yumoxu** [comment]
@Dceaser NIST should provide you with the source documents, which are not publicly available on the website. I am not very sure about how the login account works, but if you cannot find the source documents, maybe requesting it again from NIST (following the steps on the website) is a good idea.

**Comment by Dceaser** [comment]
@yumoxu Thanks for your answer, I have requested it again.
