### ISSUE TITLE
DUC Preprocessing

### ISSUE THREAD

**Issue by wglazer** [yumoxu/querysum#7]
There appears to be an issue with the default DUC filenames where the pipeline cannot identify the gold summaries corresponding to the predicted summaries while executing `python src/frame/centrality/centrality_qa_tfidf_hard.py`

For reference here is what my directory look like:
Predicted: `rank/centrality-hard_bias-0.85_damp-qa_records-qa-bert-narr-ir-tf-2007-90_qa_topK-4_wan/2007_D0701A`
Target: `data/summary_targets/2007/D0701.M.250.A.A`

And this is my stacktrace:

```
Traceback (most recent call last):
  File "src/frame/centrality/centrality_qa_tfidf_hard.py", line 273, in <module>
    select_e2e()
  File "src/frame/centrality/centrality_qa_tfidf_hard.py", line 164, in select_e2e
    select_sent.select_end2end(**params)
  File "/data/src_copy/clab-lm1271-summarization/summarization/querysum/src/summ/select_sent.py", line 326, in select_end2end
    output = rouge.compute_rouge_end2end(**text_params)
  File "/data/src_copy/clab-lm1271-summarization/summarization/querysum/src/summ/compute_rouge.py", line 166, in compute_rouge_end2end
    return compute_rouge(**rouge_paras)
  File "/data/src_copy/clab-lm1271-summarization/summarization/querysum/src/summ/compute_rouge.py", line 152, in compute_rouge
    output = r.convert_and_evaluate()
  File "/home/williamg/anaconda3/envs/querysum/lib/python3.6/site-packages/pyrouge/Rouge155.py", line 361, in convert_and_evaluate
    rouge_output = self.evaluate(system_id, rouge_args)
  File "/home/williamg/anaconda3/envs/querysum/lib/python3.6/site-packages/pyrouge/Rouge155.py", line 331, in evaluate
    self.write_config(system_id=system_id)
  File "/home/williamg/anaconda3/envs/querysum/lib/python3.6/site-packages/pyrouge/Rouge155.py", line 315, in write_config
    self._config_file, system_id)
  File "/home/williamg/anaconda3/envs/querysum/lib/python3.6/site-packages/pyrouge/Rouge155.py", line 270, in write_config_static
    id, model_dir, model_filename_pattern)
  File "/home/williamg/anaconda3/envs/querysum/lib/python3.6/site-packages/pyrouge/Rouge155.py", line 500, in __get_model_filenames_for_id
    "{}".format(id, model_filenames_pattern))
Exception: Could not find any model summaries for the system summary with ID 2007_D0701A. Specified model filename pattern was: #ID#_[\d]
```

The referenced pattern appears to be in `src/summ/compute_rouge.py` line 145

Is there any way you could share the preprocessing/renaming done on DUC files?
(I have already converted the files to UTF-8)

**Comment by yumoxu** [comment]
Hi @williamGlazer,

Thanks for spotting this! Target summaries are named following this pattern: `[YEAR]_[CLUSTERNAME]_[SUMMARYID]`.

For instance, for cluster D0701A under DUC 2007, it has summaries: 2007_D0701A_1, 2007_D0701A_2,  2007_D0701A_3 and  2007_D0701A_4.

I cannot find the code for this pre-processing at the moment, but it can be easily implemented in a few lines. 

I have attached a snippet I just finished for your reference. Note it is not strictly tested, so for reference only. 

I will upload a script to the repo for this pre-processing later on.

Note: SUMMARYID is for distinguishing multiple summaries and the summary order does not matter.

```
import collections
import os

year = '2007'
summary_dp = f'./data/summary_targets/{year}'
fns = [fn for fn in os.listdir(summary_dp)]
cluster_names = collections.defaultdict(int)

old2new = {}  # old file name -> new file name
for fn in fns:
    cluster_name = fn.split('.')[0]
    summary_id = cluster_names[cluster_name]
    new_fn = '_'.join([year, cluster_name, str(summary_id)])
    old2new[fn] = new_fn
    cluster_names[cluster_name] += 1

# rename summary files
for old, new in old2new.items():
    os.rename(summary_dp+'/'+old, summary_dp+'/'+new)
```

**Comment by wglazer** [comment]
Thanks this worked!

Here is the code snippet I used:

```
import os
YEAR = 2007

path = f'data/summary_targets/{str(YEAR)}/'
files = os.listdir(path)
doc_idx_by_cluster = {}
for file in files:
    cluster_prefix, _, _, cluster_suffix, reference_id = file.split('.')
    cluster = cluster_prefix + cluster_suffix
    
    if cluster not in doc_idx_by_cluster.keys():
        doc_idx_by_cluster[cluster] = 1
    else:
        doc_idx_by_cluster[cluster] += 1
    
    idx = doc_idx_by_cluster[cluster]
    processed_name = f'{YEAR}_{cluster}_{idx}'
    os.rename(path + file, path + processed_name)
```

**Comment by JeetRoy97** [comment]
@williamGlazer @yumoxu Please help me with the steps that I need to do after the data preparation step. It is not mentioned in which order we need to execute the .py files.

**Comment by yumoxu** [comment]
@JeetRoy97 Hi there! Could you please refer to the steps in the section - Run experiments in README? If there's anything unclear, feel free to make a new issue to specify.

**Comment by JeetRoy97** [comment]
While running ir_tf.py it is showing no log files available
