### ISSUE TITLE
Model Training

### ISSUE THREAD

**Issue by wglazer** [yumoxu/querysum#8]
Hello again!

There is little documentation in the README about how to reproduce the training for the various parts included in the `model` directory. I am aware it is documented in the paper, but would it be possible to get the detailed steps/commands within this codebase to reproduce the experiments and re-create the `model.zip` contents?

Thank you for you help!

**Comment by JeetRoy97** [comment]
@yumoxu I also request for the proper steps to execute the training module.

**Comment by yumoxu** [comment]
@williamGlazer @JeetRoy97 Thanks for bringing this up! Passage-level training can be easily done via fine-tuning on SQuAD 2.0 with [HuggingFace](https://huggingface.co/transformers/custom_datasets.html#question-answering-with-squad-2-0). Sentence-level QA training requires more preparation steps, please refer to [this](https://github.com/castorini/birch/blob/master/reproduce_arxiv.md) link for details. 

Will update README to include training instructions.
