### ISSUE TITLE
No log files available- bert_qa.log not available

### ISSUE THREAD

**Issue by JeetRoy97** [yumoxu/querysum#9]
As instructed in the  readme file, to execute the ir_tf.py file, it pops an error that the log file not found. Kindly @yumoxu help with this  issue.

**Comment by Dceaser** [comment]
HI @JeetRoy97 
You can try to build a directory under the related path by yourself at the first time

**Comment by yumoxu** [comment]
Hi @JeetRoy97, please refer to the response from @Dceaser.
